//Document List data

const doclist=[
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-04 13:12:37",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-04 13:12:37",
      "id": 1,
      "title": "WILDLIFE OFFENCES IN KENYA",
      "subTitle": "",
      "description": "Points to Prove – a Guide for Prosecutors and Investigators including Sample Charges and Standard Operating Procedures",
      "country": "Kenya",
      "image": "Fisheries_RRG_Kenya.png",
      "downloadable": true,
      "pdfURL": "Fisheries_RRG_Kenya.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-04",
      "releasedBy": "",
      "forward": "The Office of the Director of Public Prosecutions, Kenya (ODPP) has long recognised that wildlife and forestry crime is a form of organised transnational crime, requiring strong investigations and robust prosecutions. Having instituted the 1 st Interagency Forum on Wildlife Related Crimes in 2013 which brought together key agencies, the ODPP, together with Kenya Wildlife Service, the National Police Service, the Kenya Revenue Authority, Department of Immigration Services, Attorney General’s Office, and Judiciary worked together to develop the first edition of the Rapid Reference Guide To Wildlife Crime, designed and initiated by Shamini Jayanathan,Barrister-at-Law with the British High Commission. Encompassing all relevant offences under existing laws at the time of publication in 2015, this was intended to be a quick reference guide for investigators and prosecutors alike.That this guidance is now in its third edition and additional volumes are being developed to include forestry and marine crime and even fisheries offences, is testament to its utility. This is further borne out by this model being replicated across the continent and even further afield.I am proud to be associated with this Rapid Reference Guide that will undoubtedly continue to serve as a valuable resource to investigators and prosecutors and I wish to commend its use to all of the stakeholders involved in the fight to protect Kenya’s natural heritage.With grateful acknowledgement to my team within the ODPP, the Kenya Wildlife Service, the United Nations Office of Drugs and Crime and Space for Giants in their tireless efforts to keep abreast of the developments in this important and increasingly complex area of crime.",
      "acknowledgement": "",
      "accessType": "default",
      "language": "English",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "kenya-flag-icon.svg"
    },
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-05 09:49:47",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-05 09:49:47",
      "id": 3,
      "title": "WILDLIFE OFFENCES IN UGANDA",
      "subTitle": "",
      "description": "“Points to Prove” – a Guide for Prosecutors and Investigators including Sample Charges and Standard Operating Procedures",
      "country": "Uganda",
      "image": "Final_2018_RRG_Uganda.png",
      "downloadable": true,
      "pdfURL": "Final_2018_RRG_Uganda.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-05",
      "releasedBy": "",
      "forward": "",
      "acknowledgement": "",
      "accessType": "default",
      "language": "English",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "uganda-flag-icon.svg"
    },
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-05 09:47:08",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-05 09:47:08",
      "id": 2,
      "title": "GUIDE DE RÉFÉRENCE RAPIDE",
      "subTitle": "",
      "description": "À L’USAGE DES ACTEURS DE LA CHAINE PÉNALE DANS LA LUTTE CONTRE L’EXPLOITATION ILLICITE DES RESSOURCES NATURELLES",
      "country": "CAMEROUN",
      "image": "GRR_CAMEROUN_Rev.png",
      "downloadable": true,
      "pdfURL": "GRR_CAMEROUN_Rev.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-05",
      "releasedBy": "",
      "forward": "",
      "acknowledgement": "",
      "accessType": "default",
      "language": "French",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "cameroon-flag-icon.svg"
    },
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-05 09:52:51",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-05 09:52:51",
      "id": 4,
      "title": "A RAPID REFERENCE GUIDE FOR INVESTIGATORS AND PROSECUTORS",
      "subTitle": "",
      "description": "TANZANIA INVESTIGATION AND PROSECUTION OF WILDLIFE AND FORESTRY CRIME",
      "country": "Tanzania",
      "image": "RRG_Eng_Tanzania.png",
      "downloadable": true,
      "pdfURL": "RRG_Eng_Tanzania.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-05",
      "releasedBy": "",
      "forward": "",
      "acknowledgement": "",
      "accessType": "default",
      "language": "English",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "tanzania-flag-icon.svg"
    },
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-05 09:59:05",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-05 09:59:05",
      "id": 6,
      "title": "GUÍA DE REFERENCIA RÁPIDA PARA LA INVESTIGACIoN de  DELITOS forestales",
      "subTitle": "Herramienta técnica para fiscales e investigadores",
      "description": "RGUÍA DE REFERENCIA RÁPIDA PARA LA INVESTIGACIoN de  DELITOS forestales Herramienta técnica para fiscales e investigadores",
      "country": "Peru",
      "image": "RRG_Forest_Crime_Peru_ES.png",
      "downloadable": true,
      "pdfURL": "RRG_Forest_Crime_Peru_ES.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-05",
      "releasedBy": "",
      "forward": "",
      "acknowledgement": "",
      "accessType": "default",
      "language": "French",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "peru-national-flag-icon.svg"
    },
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-05 09:56:20",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-05 09:56:20",
      "id": 5,
      "title": "RAPID REFERENCE GUIDE FOR the INVESTIGATION OF FOREST CRIME",
      "subTitle": "technical toolkit for investigators and prosecutors",
      "description": "RAPID REFERENCE GUIDE FOR the INVESTIGATION OF FOREST CRIME Technical Toolkit for Investigators and Prosecutors",
      "country": "Peru",
      "image": "RRG_Forest_Crime_Peru_EN.png",
      "downloadable": true,
      "pdfURL": "RRG_Forest_Crime_Peru_EN.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-05",
      "releasedBy": "",
      "forward": "",
      "acknowledgement": "",
      "accessType": "default",
      "language": "English",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "peru-national-flag-icon.svg"
    },
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-05 10:05:45",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-05 10:05:45",
      "id": 7,
      "title": "WILDLIFE CRIME IN NIGERIA",
      "subTitle": "",
      "description": "“Points to Prove”: A Guide for Prosecutors and Investigatorss",
      "country": "Nigeria",
      "image": "Nigeria_Wildlife_Crime_RRG.png",
      "downloadable": true,
      "pdfURL": "Nigeria_Wildlife_Crime_RRG.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-05",
      "releasedBy": "",
      "forward": "Biodiversity loss is a global phenomenon in most countries of the world and has received concern in recent years owing to its threat of genetic erosion of soil fauna and flora, marine and aquatic species, social-economic poverty, deprivation of rural communities, poaching, forest and land degradation,bush fire, increase in illegal trafficking of wildlife, ecosystem imbalance, environmental pollution, habitat modifications, and alteration, national security, and public health risks, terrorism, climate change,reduction in national Gross Domestic Product accrued revenue coming from legal trade in these species.Nigeria is rich in wildlife resources ranging from unique endemic species found across different vegetation belts in the country. Despite this, Nigeria, in recent years is known to be a source, consumption, and destination hub and is currently battling the menace of illegal wildlife crime within its exit borders, in recent years.However, Nigeria has evolved several mechanisms to combat illegal wildlife trade through the setting up of the Joint Task Force in combating illegal wildlife trade, committee on seizure,participation in world wildlife day and other days celebration, harmonization of states wildlife laws with Federal Laws, aggressive sensitization awareness campaign, and the about to be completed Memorandum of Understanding (MOU) in fighting cross border ecosystem in forestry wildlife between the Government of Nigeria and Cameroon, the establishment of critical National Stakeholders’Forum of relevant MDAs in combatting illegal wildlife trade and strengthening enforcement capacity through the administration of training for Investigators, Prosecutors, Judges, and the Nigeria Customs Service and National Environmental Standards and Regulations Enforcement Agency (NESREA). The outcome of these interventions has led to the recent arrest and seizure of wildlife specimens at different border posts.Nigeria Launched its National Strategy to combat wildlife and Forest Crime in Nigeria (2022- 2026) with sets out Seven objectives which include: institutional commitment, defined organizational structures, and capabilities to effectively address both transnational and domestic wildlife crime. The second objective seeks to strengthen the Legal Framework as this will enable legal and sustainable trade, protect Nigeria’s fauna and flora, and deter wildlife crime through a harmonized and strengthened legal framework.The development of Nigeria’s Wildlife Crime Rapid Reference Guide for Investigators, Prosecutors,and Judges is timely as this will not only help harmonize the existing legal framework in enforcement and prosecuting environmental criminal syndicates but also serve as a Standard Operating procedure (SOP) for the prevention, investigation, and prosecution of wildlife crime thereby reducing the lengthy investigation and prosecution time.I will like to commend the collaboration of all critical stakeholders who have worked assiduously with the Federal Ministry of Environment in the production of this document; the United Nations Office on DrugsWildlife Crime in Nigeriaiv and Crime, Africa Nature Investors (ANI) Foundation, National Park Service, NESREA, Nigeria Customs Service (NCS), Federal Ministry of Justice DPP, Cross Rivers State DPP, and Lagos State DPP.Special thanks to our Development Partner, the German Government for the release of funds at different stages of production of this document. I believe the efforts put into the production of this document will facilitate prompt prosecution of illegal wildlife crime cases in Nigeria.",
      "acknowledgement": "",
      "accessType": "default",
      "language": "English",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "nigeria-flag-icon.svg"
    },
    {
      "createdBy": "jhonmiller@mailinator.com",
      "createdDate": "2023-07-05 10:11:05",
      "lastModifiedBy": "jhonmiller@mailinator.com",
      "lastModifiedDate": "2023-07-05 10:11:05",
      "id": 8,
      "title": "Rapid Reference Guide For the investigation and prosecution of wildlife crime in the Philippines",
      "subTitle": "",
      "description": "Rapid Reference Guide For the investigation and prosecution of wildlife crime in the Philippines",
      "country": "Philippines",
      "image": "RRG_Philippines_09_18_Dec_2020.png",
      "downloadable": true,
      "pdfURL": "RRG_Philippines_09_18_Dec_2020.pdf",
      "offline": true,
      "available": true,
      "accessable": false,
      "version": 1,
      "releaseDate": "2023-07-05",
      "releasedBy": "",
      "forward": "Wildlife trafficking is a serious crime affecting Southeast Asia and the whole World. The Republic ofthe Philippines is not immune to the detrimental effects that wildlife trafficking has on theenvironment, on the rule of law and on human health. By illegally taking wild animals from theirnatural ecosystem and bringing them to our cities for commercial purposes we are exposing oursociety to risks that cannot be controlled, under-pinning the need to combat the illegal trade of wildflora and fauna as a battle to protect the planet and the health of our society.The Rapid Reference Guide for the investigation and prosecution of wildlife crime in the Philippines isa practical tool to improve the way in which the most serious forms of wildlife crimes are handled inline with our legal framework, with our procedures and with our legal tradition. The Guide willundoubtedly serve as a valuable resource for investigators and prosecutors and I encourage its use toall stakeholders involved in the fight against the scourge of wildlife crime.This Guide has been developed during the months of lockdown and restrictive measures enforcedacross the Country after the outbreak of the COVID-19 pandemic. For this reason, I would like toextend my gratitude to all those experts that despite existing restrictions on face-to-face interactionshave lent their support to the development of this important document.We thank the United Nations Office on Drugs and Crime, which worked very closely with theBiodiversity Management Bureau to develop this Guide through consultation with a number of legalexperts and practitioners across the country. We are also pleased that the Guide has been turned intoan application for mobile phones and tablets, with a view to make it even more accessible to allinvestigators and prosecutors across the Philippines.The Government of the Philippines remains committed to preserve the rich biodiversity of the Countryand to be an active player in the global efforts to combat the illegal trade in endangered wildlife.",
      "acknowledgement": "The United Nations Office on Drugs and Crime (UNODC) wishes to express appreciation to all involved in the development and facilitation of the Rapid Reference Guide for the investigation and prosecution of wildlife crime in the Philippines.The development of the Guide was supported by Mr. Ray A. Cimatu, Secretary of Environment and Natural Resources and it was spearheaded by Mr. Ricardo L. Calderon, OIC Assistant Secretary for Climate Change and concurrent Director of the Biodiversity Management Bureau (BMB) of the Department of Environment and Natural Resources (DENR). Mr. Calderon appointed a working group lead by Atty. Theresa Tenazas, OIC of the Wildlife Resources Division, which was responsible for ensuring the involvement and consultation of all relevant departments of the Government at national and provincial levels. The tireless effort, dedication, and level of devotion of the working group, which undertook this task in a period of lockdown and adjustments related to a global pandemic including a new normal of remote meetings, is recognized and is highly valued.UNODC is also grateful to the various Government institutions and organizations that supported and participated in the validation process, including the Anti-Money Laundering Council Secretariat, Bureau of Customs, National Bureau of Investigations, National Prosecution Service under the Department of Justice, Office of the Special Envoy on Transnational Crime, Philippine Coast Guard, Philippine National Police, and the ADB/GEF-DENR project on Combating Environmental Organized Crime in the Philippines.The development and facilitation of the Rapid Reference Guide was led by international consultant Salvatore Amato, along with the valuable assistance of national experts Andrew Felix Arsenio A. De Castro, C. Therese Guiao and Justine Nicole Torres.UNODC facilitated this process through its Global Programme for Combating Wildlife and Forest Crimes and the involvement of its staff Giovanni Broussard, Zhiqiang Tao and Christel Joy Martinez.The Rapid Reference Guide was made possible thanks to a generous contribution from the Bureau of International Narcotics and Law Enforcement Affairs (INL) of the United States Department of State.",
      "accessType": "default",
      "language": "English",
      "annexure": "",
      "hasAnnexure": true,
      "flagPath": "philippines-flag-icon.svg"
    }
  ]

const userlist = [
    {
        "id":"1",
        "name":"John Doe",
        "email":"john.doe@gmail.com",
        "country":"Kenya",
        "status":"active"
    },
    {
        "id":"2",
        "name":"John Doe",
        "email":"john.doe@gmail.com",
        "country":"Kenya",
        "status":"active"
    },
    {
        "id":"3",
        "name":"John Doe",
        "email":"john.doe@gmail.com",
        "country":"Kenya",
        "status":"active"
    },
    {
        "id":"4",
        "name":"John Doe",
        "email":"john.doe@gmail.com",
        "country":"Kenya",
        "status":"active"
    },
    {
        "id":"5",
        "name":"John Doe",
        "email":"john.doe@gmail.com",
        "country":"Kenya",
        "status":"active"
    },
    {
        "id":"6",
        "name":"John Doe",
        "email":"john.doe@gmail.com",
        "country":"Kenya",
        "status":"active"
    },
]

const countries = [
  {
    "createdBy": null,
    "createdDate": null,
    "lastModifiedBy": null,
    "lastModifiedDate": null,
    "id": 3,
    "name": "Kenya",
    "code": null,
    "description": null,
    "remarks": "kenya",
    "latitude": 0,
    "longitude": 0,
    "deleted": null
  },
  {
    "createdBy": null,
    "createdDate": null,
    "lastModifiedBy": null,
    "lastModifiedDate": null,
    "id": 5,
    "name": "Nigeria",
    "code": null,
    "description": null,
    "remarks": "Nigeria",
    "latitude": 0,
    "longitude": 0,
    "deleted": null
  },
  {
    "createdBy": null,
    "createdDate": null,
    "lastModifiedBy": null,
    "lastModifiedDate": null,
    "id": 4,
    "name": "Peru",
    "code": null,
    "description": null,
    "remarks": "Peru",
    "latitude": 0,
    "longitude": 0,
    "deleted": null
  },
  {
    "createdBy": null,
    "createdDate": null,
    "lastModifiedBy": null,
    "lastModifiedDate": null,
    "id": 7,
    "name": "Tanzania",
    "code": null,
    "description": null,
    "remarks": "Tanzania",
    "latitude": 0,
    "longitude": 0,
    "deleted": null
  },
  {
    "createdBy": null,
    "createdDate": null,
    "lastModifiedBy": null,
    "lastModifiedDate": null,
    "id": 6,
    "name": "Uganda",
    "code": null,
    "description": null,
    "remarks": "Uganda",
    "latitude": 0,
    "longitude": 0,
    "deleted": null
  }
]

const quizData = [
  {
      "id":"1",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  },
  {
      "id":"2",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  },
  {
      "id":"3",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  },
  {
      "id":"4",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  },
  {
      "id":"5",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  },
  {
      "id":"6",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  },
  {
      "id":"7",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  },
  {
      "id":"8",
      "title":"Basic fundamentals of wild life in Kenya",
      "questions":"25",
      "qualify":"75",
      "level":"Moderate",
      "duration":"30"
  }
]

export {doclist, userlist, quizData}